#!/bin/bash

gcc -Wall -Wextra -Werror -pedantic -std=gnu89 -g shell.c strings.c path.c execute_command.c read_interactive_command.c parse_command.c free_mem.c find_exe.c tokenize_path.c tokenize_command.c -o test_hsh

./test_hsh